language: generic
env:
  global:
  - GCP_PROJECT_ID=devops-gcp-project-296222
  - tf_version=0.13.5
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - secure: RJ5bt1G8WOK42zHHzLkViHK+gHi8+F+BPOJQ+6MHmv82UYftDBh2aPN7T6ZDszs0rYJjXHhhKpazi9SO+1yGA/nbWg+0Vm8kYcRHa2bdWmDY06VApc4BIH5jzXoIb/dQo6A1LJS6sI9JcW2lF9/GsHRHQbf1LYr+meFs1VZ0c+VR26Ev0R97KqfQ0mh/Q11sZdpJDIg0o7HMCY5yyD/6tcq7pPYTVqxlK/GNBIIIfV/JAleCdmkhnDEg7SSMh6R1p3tugBr88YETnevnyPwkL8PEOQD9X0a585xK9cO4ZYqTAZwQ3lOu/E20/P4BYuyWwCDuWArXbDIW5cm/2LkyDyPj9nUIU+tAv7oY7b/43SOGapHVozrCuNKakshM4aGPhe2Dm53g/NDj7eaMIQG6wtupXalUSWWA6lf5EKM2kLB/9oKwJdTaZf/jYs6nyNCbTyo6KrB/DGG/8WVFEtCypPmrkavnctc9s/SIenpl9chwDSnAniEtJ5KSybHtgSKeAvyj2zEdXVSMfDih9TiKlzNizFz2bNt15NdlQoe9VVxPXKND4JGYOrt7YDJ+Dck//dg9zXbFVn6VL8zrVaL6ExBJ2YBTiY7Wf94mldoTtILjHbsBEcQPjVdSw9ylc82co/4mLsKg6ylDA7M3z76sPIznZkPbEMrGEQtZNZ8QHZw=
  - secure: "KgIs44RKSxlyvKbTVqDz5WezqTA7qR6c80jOr7zzDA/1NB3lx6xGCp9bn/PDEKC/qobL221L6f04Qye7u2kfxm6gIu0/2zRJRqEJIhqxyEVG4k5CiAVRENOfglvGBcADZTKqjfxPfbiXDIElY6QtevPdyPWhkyZQGcoVjbU4dxmd2fnc8WdpP4hRHGMVOgdgrN91wWFsQZ7D4ON4vhsA8Nez1DjhqdVsq4o8CH3CGhUgjd4FWbtb70tM7G5fH3XI8tUgxdCWr7LnjdB5FrR+A+1LoWaQk7YGGFK+fXJiebemG/Ttk9Yx09NHTmk+tNaLL/nI0LG0HO6AKUKLO2jaEXPqquSWjwnq31X5SJC61kcYc5Tef3tDvkkULkvWaOEjknxIIxp3W8fWJJ9LpnomiRjVH194v6/7GvKyDeeLpnH/Pbz/WeI3vuPL+MCi555pzbWL3P1dAM4YHGiC5AqOUD5cFj9R4/4AfHiMIId6bxustyOIBGYWwDIsBwx50oa5Xqv8gl5sklm2lv4Yv5vM2fAxsguT/KEhbltjKEb/MzjClqDz9DF+8GKW9ScOQAUqWtzplb++Axu820XHnBpNqeJRDbdG3Xv2p5lrJCVfeiPz4zUeJ96t51pX4n1eEbMhm7em6mObusEwvJSuWY8eybFDUH0a2FUvbw8Nw3BBkKg="

branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_32f589868c05_key -iv $encrypted_32f589868c05_iv
  -in devops-gcp-project-296222-41ee350b7bd5.json.enc -out devops-gcp-project-296222-41ee350b7bd5.json
  -d
- curl https://sdk.cloud.google.com | bash > /dev/null
- source "$HOME/google-cloud-sdk/path.bash.inc"
- gcloud auth activate-service-account --key-file=devops-gcp-project-296222-41ee350b7bd5.json
- gcloud config set project "${GCP_PROJECT_ID}"
- export GOOGLE_APPLICATION_CREDENTIALS=devops-gcp-project-296222-41ee350b7bd5.json
- wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
- unzip terraform_"$tf_version"_linux_amd64.zip
- sudo mv terraform /usr/local/bin/
- rm terraform_"$tf_version"_linux_amd64.zip
install: true
script:
- |-
  set -ex;
  export TF_VAR_logz_token=$LOGZ_TOKEN
  export TF_VAR_status_cake=$STATUS_CAKE
  terraform init
  terraform plan
  terraform apply --auto-approve
  terraform output
