language: generic
env:
  global:
  - GCP_PROJECT_ID=devops-gcp-project-296222
  - tf_version=0.13.5
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - secure: RJ5bt1G8WOK42zHHzLkViHK+gHi8+F+BPOJQ+6MHmv82UYftDBh2aPN7T6ZDszs0rYJjXHhhKpazi9SO+1yGA/nbWg+0Vm8kYcRHa2bdWmDY06VApc4BIH5jzXoIb/dQo6A1LJS6sI9JcW2lF9/GsHRHQbf1LYr+meFs1VZ0c+VR26Ev0R97KqfQ0mh/Q11sZdpJDIg0o7HMCY5yyD/6tcq7pPYTVqxlK/GNBIIIfV/JAleCdmkhnDEg7SSMh6R1p3tugBr88YETnevnyPwkL8PEOQD9X0a585xK9cO4ZYqTAZwQ3lOu/E20/P4BYuyWwCDuWArXbDIW5cm/2LkyDyPj9nUIU+tAv7oY7b/43SOGapHVozrCuNKakshM4aGPhe2Dm53g/NDj7eaMIQG6wtupXalUSWWA6lf5EKM2kLB/9oKwJdTaZf/jYs6nyNCbTyo6KrB/DGG/8WVFEtCypPmrkavnctc9s/SIenpl9chwDSnAniEtJ5KSybHtgSKeAvyj2zEdXVSMfDih9TiKlzNizFz2bNt15NdlQoe9VVxPXKND4JGYOrt7YDJ+Dck//dg9zXbFVn6VL8zrVaL6ExBJ2YBTiY7Wf94mldoTtILjHbsBEcQPjVdSw9ylc82co/4mLsKg6ylDA7M3z76sPIznZkPbEMrGEQtZNZ8QHZw=
  - secure: "elFedyWC/csGOFUTIi6BGo9fKpD5t+UmztJLfgq+DpT6Dfdx7q1YrBbZuWQQgcp8tH9lnUtQDH3Fzgg/OrtjrWJJem40WfGgK0VD2WlLwy4W8FezRB2Kvcokpc3XLaz/PhlszUVnq5bMAhydFdaS67ZT5JNJxPAHA4zu/neS1VxnWiVVePwAysW+ce3pHm4XeHlgsPW8SFuAj1WLiiUwGOjn8qCfeBH5QQJ05SZloduXMkzlGP1JZWPrvuuvg8cEwHR7i6fGMte9nMVkANPis46+TLPLXNdyxD4PVLBsJf/0Iza3KAWTRN10hK4ut4gpEzeRLzTX7T7nCFj5DPa72nYu1Pvz+B66B7n6dLY3Jt++DUmpTsRgOtYh6uuuKzhMPGna99Rl/9HaW/axAnAC4Mezm9MSrKeaf040vIXV/pLF3FxBrmm41xfdf2BugxZCwPFPD78EpxN1aSpogfOwP04Bn0i2NfMWWI7fdF99nje340Yp6HXTbBx477fUazrsU2q4BlTrchxl1CZV5AMQ9KtRU+0LnWl3ctSP1nV0O6t/mZ2WKrCjEZrGtltW8kzGdZwVQpmC9fn6T7zfjs9cMiUAJ3/42SFiAdRspKRsELTnT7yAn0irpGAXa5j7FMrrU8uXkF8DFSr1sGqvAd5w/Pzy4MzLL6ini04yDZltI9E="


branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_32f589868c05_key -iv $encrypted_32f589868c05_iv
  -in devops-gcp-project-296222-41ee350b7bd5.json.enc -out devops-gcp-project-296222-41ee350b7bd5.json
  -d
- curl https://sdk.cloud.google.com | bash > /dev/null
- source "$HOME/google-cloud-sdk/path.bash.inc"
- gcloud auth activate-service-account --key-file=devops-gcp-project-296222-41ee350b7bd5.json
- gcloud config set project "${GCP_PROJECT_ID}"
- export GOOGLE_APPLICATION_CREDENTIALS=devops-gcp-project-296222-41ee350b7bd5.json
- wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
- unzip terraform_"$tf_version"_linux_amd64.zip
- sudo mv terraform /usr/local/bin/
- rm terraform_"$tf_version"_linux_amd64.zip
install: true
script:
- |-
  set -ex;
  export TF_VAR_logz_token=$LOGZ_TOKEN
  export TF_VAR_status_cake=$STATUSCAKE_APIKEY
  terraform init
  terraform plan
  terraform apply --auto-approve
  terraform output
